name: Deploy Application

on:
  push:
    branches:
      - main


jobs:
  create-deployment-artifacts:
    name: Create deployment-artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - name: compile CSS and Javascript
        run: |
          npm install
          npm run build